# Dev Containerではこちらが優先される。
services:
  go-app:
    build:
      target: devcontainer
      context: .
      dockerfile: Dockerfile
    image: go-devcontainer-img:latest
    container_name: go-devcontainer
    volumes:
      - ./:/app # contextから見たパスではなく，リポジトリから見たパスがvolume mountされる。
